import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";

const raleway = Raleway({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-raleway',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} font-sans antialiased scroll-smooth overflow-x-hidden w-full`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
